### PR TITLE
Shadows on hover for timeline

### PR DESCRIPTION
**Pull request by trexdinosaur**
Gives a bit more dimension:
https://imgur.com/a/pSCqT

Thanks

### CODE REVIEW

**Comment by uttu357** [comment]
@aka-jain Can you have a look at this. Is the extra shadow required?

**Comment by gautamjajoo** [comment]
@aka-jain Do we need the extra shadow here??

**Comment by aka-jain** [comment]
@gautamjajoo the news cards are not links so there is no need to add hover effect on these cards. 
cc @uttu357

**Comment by gautamjajoo** [comment]
@trexdinosaur Hence closing this PR.

**Comment by pavanagrawal123** [comment]
Please do note that the icons for the external projects and sponsors were links, but this PR didn't select specifically for them, it selected cards in general.

**Pull request closed without merging**
