### PR TITLE
Fix #38: Fix styles for homepage's screenshot image file input field

### LINKED ISSUE #38: Screenshot image file input in homepage does not have any styles.
File input on the homepage is not styled.
- The contact-us form in the [homepage](http://cloudcv.us-west-2.elasticbeanstalk.com/contact-us) contains a file input which is not styled and have default html styles. The current form looks like 

image

- It can be styled using a wrapper container around the input block. I have changed the styles in my browser's console and now the form looks like

image

- The design of input can be altered as per need.

I would like to work to resolve this UI issue.

### PR DESCRIPTION
**Pull request by fristonio**
Fix #38:

- UI in the homepage of input field is changed from html's default to style matching homepage's theme.

### CODE REVIEW

**Comment by fristonio** [comment]
@uttu357 can you please review :slightly_smiling_face:

**Comment by fristonio** [comment]
I forgot to change the text of the input once the file upload completes. Saw it in @trexdinosaur PR, fixed it here. Please mention if some other changes are required. :slightly_smiling_face:

**Comment by uttu357** [comment]
LGTM. Good work! :+1: Merging.

**Comment by fristonio** [comment]
Thanks @uttu357  @deshraj :slightly_smiling_face:

**Pull request merged**
