### PR TITLE
Broken demo log

### PR DESCRIPTION
**Pull request by adamstafa**
`sendBrokenDemo()` still needs some changes. It sends the request but Django throws error.

I also fixed height of the iframe. It was set to 100%, but there was another children in the parent div so the iframe was pushed  a bit downwards.

### CODE REVIEW

**Comment by adamstafa** [comment]
I removed hard-coded `log_type='Submission'`. It now depends on `log_type` specified in the POST request. The log now shows properly in the admin panel.

**Comment by uttu357** [comment]
@adamstafa Also edit other pieces of code where logs with log_type = "Submission" are saved.

**Comment by uttu357** [comment]
I am still getting a 404 error when I click on the Demo Not working button. Also change its style to look like a button.

**Comment by adamstafa** [comment]
@uttu357  `post_log` in `apps/logs/views.py` is also used for saving input (there's also a method in `DemoContainer.js` for it). Now there are two options:

- Use `post_log` for both Submission and Break and place there if block just for Submissions .
- Create new view for Submissions and move its URL to `/api/logs/<permalink>/add/input`. I would use `post_log` only for Break logs then.

Which option do you prefer?

About the button: Could it look like the **SOURCE CODE** button on the home page?? 
image

**Comment by adamstafa** [comment]
So this is the first option, no more 404s.

I tried adding some borders to the button so it looks more like a button, but they all looked kinda weird. IMHO plain text as on the home page looked the best.

**Comment by uttu357** [comment]
LGTM! Merging! :+1:

**Pull request merged**
