### PR TITLE
Added GCI section 

### LINKED ISSUE #61: Add Google Code-In links
## Deliverables

- [ ] Add the GCI logo with proper hyperlinking in the "Interested in Contributing" section
- [ ] Add the GCI link on CloudCV Header

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes #61 
Updated News Section and Added the GCI section in Contribution.
 @uttu357

### CODE REVIEW

**Comment by gautamjajoo** [comment]
The checks are failed. Will see the reason and will update!

**Comment by deshraj** [comment]
@gautamjajoo: any update on this?

**Comment by gautamjajoo** [comment]
What should I do as checks are failing!!@Deshraj

**Comment by deshraj** [comment]
Seems like the JS code is not formatted properly. See the error here: https://travis-ci.org/Cloud-CV/CloudCV/builds/324987421#L843

**Pull request closed without merging**
