### PR TITLE
GCI Task: Added about tabs to the demos

### PR DESCRIPTION
**Pull request by PalashTanejaPro**
Added about tabs as asked in a GCI Task. 
- Created partial style _tabs.scss
- Installed package react-tabs
- Currently, about tab displays demo description, this has to be changed accordingly.

Screenshots
Demo showing my personal website
<br>
About Tab showing demo description

### CODE REVIEW

**Comment by uttu357** [comment]
@PalashTanejaPro The travis build is failing. Can you fix that so that this PR can be tested.

**Comment by PalashTanejaPro** [comment]
@uttu357 Fixed!

**Comment by uttu357** [comment]
@PalashTanejaPro In the about section first show the name of the demo in the center. Then description and a link to the source code. Add information about relevant paper if it is present in the database. Rest looks fine. :+1:

**Comment by PalashTanejaPro** [comment]
@uttu357 Added the details that you requested. 
Here is a screencap
image

**Comment by PalashTanejaPro** [comment]
@uttu357 Made the requested changes.

**Comment by uttu357** [comment]
LGTM! :+1: Merging.

**Pull request merged**
