### PR TITLE
GCI demos carousel

### PR DESCRIPTION
**Pull request by adamstafa**
Finally working version of the carousel.

### CODE REVIEW

**Comment by uttu357** [comment]
Good work @adamstafa. There are a few issues before we can test this PR that needs to be resolved.
- Run `npm run lint:build` on your local machine. This will show the linting errors that are failing the Travis CI build. Resolve them and ask if you are stuck somewhere on the Gitter Channel.
- Also install [EditorConfig](http://editorconfig.org/) for the text editor/IDE you are using. EditorConfig locks the styling and spacing of the code according to the `.editorconfig` file present in the root directory.

**Comment by uttu357** [comment]
@adamstafa I tested it at dev1.cloudcv-dev.ml. The UI seems to break for long descriptions. Can you strip the description to the first 10-15 characters and show `...` at the end of it so that the card height remains manageable?

**Comment by uttu357** [comment]
@adamstafa Good work.. :+1:  Can you remove the box shadow on the carousel when the demos are more than 2. Also change the website link to `/projects/{demo.permalink}`. After this I think it can be merged.
I will create another task for making the carousel mobile responsive.

**Comment by adamstafa** [comment]
So I change `<Link to={demo.demo_url} target="_blank">` to `</projects/{demo.permalink} target="_blank">`?

**Comment by uttu357** [comment]
Yeah. It wont work like that you would have to use ``to={`/projects/${demo.permalink}`}`` and change the button text to "Demo".

**Comment by uttu357** [comment]
LGTM! Merging. :+1:

**Comment by adamstafa** [comment]
Perfect 😄

**Pull request merged**
