### PR TITLE
Added GCI in Contributing Section

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes first part of #61 .

### CODE REVIEW

**Comment by uttu357** [comment]
@gautamjajoo There are some linting errors in your code. Can you check them?

**Comment by RishabhJain2018** [comment]
@gautamjajoo Can you please fix the travis build?

**Comment by uttu357** [comment]
@gautamjajoo The travis build is still failing

**Comment by gautamjajoo** [comment]
Closing this, #90 .

**Pull request closed without merging**
